language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.4.2
  - DJANGO_VERSION=1.5a1
install:
  - pip install Django==$DJANGO_VERSION --index-url=http://pypi.renie.fr/
script:
  - python setup.py test
