language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - DJANGO_VERSION=1.4.3
  - DJANGO_VERSION=1.5c1
install:
  - pip install Django==$DJANGO_VERSION --index-url=http://pypi.renie.fr/
script:
  - python setup.py test
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.4.3
