language: python
python: 3.6
sudo: false
env:
  - TOXENV=py27-django111
  - TOXENV=py34-django111
  - TOXENV=py35-django111
  - TOXENV=py36-django111
  - TOXENV=docs
  - TOXENV=lint
install:
  - pip install tox
script:
  - tox -e $TOXENV
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5  # https://github.com/travis-ci/travis-ci/issues/4794
